- name: Varibels 
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: PLAY 1
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "{{COURSE}} course is can complte {{DURATION}} if you trained under {{TRAINER}}"
  - name: PLAY 2
    ansible.builtin.debug:
      msg: "{{COURSE}} course is can complte {{DURATION}} if you trained under {{TRAINER}}"
