- name: Varibels 
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: please enter course name
  - name: DURATION
    prompt: please enter DURATION name
  - name: TRAINER
    prompt: please enter TRAINER name

  tasks:
  - name: PLAY 1
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "{{COURSE}} course is can complte {{DURATION}} if you trained under {{TRAINER}}"
  - name: PLAY 2
    ansible.builtin.debug:
      msg: "{{COURSE}} course is can complte {{DURATION}} if you trained under {{TRAINER}}"
