- name: conditions
  hosts: local
  connection: local
  vars:
    number: 15
  tasks:
  - name: play1
    ansible.builtin.debug:
      msg: "when {{ number }} the less than 15"
    when: number > 10

    
  - name: play2
    ansible.builtin.debug:
      msg: "when {{ number }} is greter than 15"
    when: number > 15
