- name: install based os
  hosts: web
  tasks: 
  - name: install nginx in redhat
    ansible.bulitin.dnf:
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install nginx in ubuntu
    ansible.bulitin.apt:
      state: installed
    when: ansible_os_family == "Debian"
    
  