- name: install soft
  hosts: web
  become: yes
  tasks: 
  - name: install softs
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - {name: 'git' , state: 'prasent'}
    - {name: 'gcc' , state: 'prasent'}
    - {name: 'mysql' , state: 'absent'}
    - {name: 'zip' , state: 'absent'}
